server:
  port: 8085

spring:
  application:
    name: springboot-security-InKy0
  datasource:
    url: jdbc:mysql://localhost:3306/security_basic?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  data:
    redis:
      port: 6379
      host: localhost
      password: 1234

